import GoogleAnalytics from "@/components/GoogleAnalytics";
import "./globals.css";

// const poppins = Poppins({subsets:['latin'],weight:['400'],variable:'--font-poppins'})

export const metadata = {
  title: "Code Mate",
  description: "Generated by create next app",
  favicon: "",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalytics GA_TRACKING_ID={process.env.GA_TRACKING_ID} />
      <body>{children}</body>
    </html>
  );
}
